dist: xenial
language: python
python:
  - "3.7"
env:
  - HEROKU_APP_NAME=rest--api
services:
  - docker
before_script:
  - docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
  - docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web .
script:
  - echo 0
after_success:
  - docker push registry.heroku.com/${HEROKU_APP_NAME}/web
  - heroku addons:create heroku-postgresql:hobby-dev --app ${HEROKU_APP_NAME}
  - heroku pg:reset --app rest--api
  - heroku pg:psql --app rest--api < schema.sql
  - heroku container:release web --app ${HEROKU_APP_NAME}