CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
    id SERIAL PRIMARY KEY,
    owner_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE RESTRICT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS issues(
    id SERIAL PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    project_id INTEGER NOT NULL REFERENCES projects ON DELETE CASCADE ON UPDATE RESTRICT,
    author_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE RESTRICT,
    status INTEGER NOT NULL DEFAULT 1 CHECK(status IN (0,1)),
    content TEXT
);

CREATE TABLE IF NOT EXISTS assignees(
    issue_id INTEGER NOT NULL REFERENCES issues ON DELETE CASCADE ON UPDATE RESTRICT,
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS labels(
    issue_id INTEGER NOT NULL REFERENCES issues ON DELETE CASCADE ON UPDATE RESTRICT,
    label VARCHAR(255) NOT NULL
);